
name: CI - Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_admin_password
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_DATABASE: test_db
          MYSQL_CHARSET: utf8mb4
          MYSQL_COLLATION: utf8mb4_unicode_ci
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Initialize database tables
        run: |
          timeout 10s npm run start:local || true
          sleep 5
        env:
          NODE_ENV: test
          PORT: 3001
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
          DB_DATABASE: test_db
          DB_SYNC: true
          DB_LOGGING: false
          SCRAPING_INTERVAL: 300000
          MAX_RETRY_ATTEMPTS: 3
          RETRY_DELAY: 1000

      - name: Run seeders
        run: npm run seed:run
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
          DB_DATABASE: test_db
          NODE_ENV: test

      - name: Run unit & integration tests with coverage
        run: npm run test:cov -- --ci
        env:
          NODE_ENV: test
          PORT: 3001
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
          DB_DATABASE: test_db
          DB_SYNC: false
          DB_LOGGING: false

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NODE_ENV: test
          PORT: 3001
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
          DB_DATABASE: test_db
          DB_SYNC: false
          DB_LOGGING: false

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          if-no-files-found: ignore

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
